import type { Metadata } from "next";
import { Lato, Josefin_Sans, Domine } from "next/font/google";
import { merge } from "@/utils";
import "./globals.css";
import Header from "@/components/header";

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lt",
  weight: "400",
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-js",
});

const domine = Domine({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={merge([
          lato.variable,
          domine.variable,
          josefin.variable,
          "font-dm bg-gray-100 text-gray-800",
        ])}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
